### ISSUE TITLE
[FEAT] Avoid duplicate family members

### ISSUE THREAD

**Issue by navascogt** [sree-hari-s/Expense-Tracker#11]
**Is your feature request related to a problem? Please describe.**
When testing the Expense-Tracker App there is no validation for family members duplicates.

**Describe the solution you'd like**
If the family member name exists avoid duplicate.

**Describe alternatives you've considered**
Check for family member already exists, instead of add new one just update it.

**Additional context**

**Comment by sree-hari-s** [comment]
#13 Issue closed
