### ISSUE TITLE
[FEAT] Add basic authentication

### ISSUE THREAD

**Issue by navascogt** [sree-hari-s/Expense-Tracker#19]
**Is your feature request related to a problem? Please describe.**
The app does not have authentication

**Describe the solution you'd like**
Authentication must be added using the Streamlit mechanism.

**Describe alternatives you've considered**
As a first step the authentication must be added with Streamlit basic mechanism, however, in a near future it must be changed to a most robust solution, using native Streamlit or using a community component, in addition a persistent mechanism must be used too, but remain agnostic in the flavor of the database, so the app could be used with any database. I will be adding a discussion regarding the database topic.

**Additional context**

**Comment by sree-hari-s** [comment]
Let's make the basic application viable, and then move forward with this issue.

**Comment by navascogt** [comment]
I Understand @sree-hari-s , thanks for the opportunity to work in your project!
