### ISSUE TITLE
[FEAT] Track the expense

### ISSUE THREAD

**Issue by sree-hari-s** [sree-hari-s/Expense-Tracker#7]
**Is your feature request related to a problem? Please describe.**
It would be better to if we are able to track to which category the expenditure happened and a description that is optional

**Describe the solution you'd like**
A drop down to categorize the expense.

**Comment by PuruSinghvi** [comment]
I think I will be able to work on this.
Please assign this to me, thanks

**Comment by aleksanderboe** [comment]
#12 
I have started on this issue here
