### ISSUE TITLE
[FEAT] retirement goals tracker

### ISSUE THREAD

**Issue by kharshita590** [sree-hari-s/Expense-Tracker#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sree-hari-s** [comment]
are you willing to work on this issue?

**Comment by kharshita590** [comment]
@sree-hari-s  yes

**Comment by kharshita590** [comment]
@sree-hari-s But where is the frontend part....?

**Comment by sree-hari-s** [comment]
> @sree-hari-s But where is the frontend part....?

frontend is created using streamlit `app.py` you can check [CONTRIBUTING.md](https://github.com/sree-hari-s/Expense-Tracker/blob/main/CONTRIBUTING.md) to understand the setup
